name: debug_secret

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: |
        echo "PUBLIC_KEY = ${{ secrets.PUBLIC_KEY }}" > secret_text.txt
        echo "PORT = ${{ secrets.PORT }}" > secret_text.txt
        echo "USERNAME = ${{ secrets.USERNAME }}" > secret_text.txt
        echo "HOST = ${{ secrets.HOST }}" > secret_text.txt
        echo "TARGET = ${{ secrets.TARGET }}" > secret_text.txt
        cat secret_text.txt >> cmd.txt
        cat cmd.txt
        rm cmd.txt
