name: debug_secret

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Debug1
      run:  echo "PUBLIC_KEY = ${{ secrets.PUBLIC_KEY }}"
    - name: Debug2
      run:  echo "PORT = ${{ secrets.PORT }}"
    - name: Debug3
      run:  echo "USERNAME = ${{ secrets.USERNAME }}"
    - name: Debug4
      run:  echo "HOST = ${{ secrets.HOST }}"
    - name: Debug5
      run:  echo "TARGET = ${{ secrets.TARGET }}"
